### ISSUE TITLE
No trade since last 36 hours

### ISSUE THREAD

**Issue by jeet2k123** [zyairelai/futures-hero#17]
Hello,

I've been running your bot for more than 36 hours on a $100 wallet but not a single trade was executed.
Is there a way to check any logs to see if there was an error executing the order like Margin insufficient?

**Comment by zyairelai** [comment]
Hi, kindly refer to this thread.
https://github.com/zyairelai/futures-hero/issues/15

Besides, to be exact, you can go to the following website:
https://www.bitmex.com/app/trade/XBTUSD

Configure the candle chart as per following: heikin-ashi candle, 6 hours interval
The entry condition is only, and only when the there is 2 solid green to long or 2 solid red candle to short.

Otherwise the bot will not take any action as when candle is having wick coming up and down of a candle, it is considered as unclear direction and this is where people get liquidated. Even in my manual trading I will take a rest when I see a candle with wick in heikin-ashi.

Hope I answer your question.

![Screenshot from 2021-05-09 13-08-07](https://user-images.githubusercontent.com/49854907/117561258-b6fdd100-b0c7-11eb-9d23-e102f85ec170.png)

**Comment by jeet2k123** [comment]
ok...thanks for the info :)

**Comment by jeet2k123** [comment]
So the bot is looking for 2 solid candles without any wicks or wick on one side only?

**Comment by zyairelai** [comment]
![Screenshot from 2021-05-09 14-27-06](https://user-images.githubusercontent.com/49854907/117562596-aa32aa80-b0d2-11eb-81e8-36c75d904055.png)

**Comment by jeet2k123** [comment]
awesome! thanks Bro!

**Comment by zyairelai** [comment]
Hi @jeet2k123 ,
Recently I had built the Discord for my Trading Bot and manual trading discussion.
Here is the invite link: https://discord.gg/r4TnhcdqmT
