### ISSUE TITLE
Last version missing strategies

### ISSUE THREAD

**Issue by josemhb** [zyairelai/futures-hero#24]
Hi folks,

In last version run.py call **_strategies.seven_** but this strategie does not exist in strategies folder.

`Traceback (most recent call last):
  File "run.py", line 5, in <module>
    import strategies.seven
ModuleNotFoundError: No module named 'strategies.seven'`

If I comment import strategies.seven in run.py code, this error disappears but another appears:

`Traceback (most recent call last):
  File "run.py", line 63, in <module>
    lets_make_some_money(pair, leverage, quantity)
  File "run.py", line 23, in lets_make_some_money
    hero = choose_your_fighter.futures_hero(pair)
  File "/home/opc/futures-hero-new/futures-hero/strategies/combined.py", line 26, in futures_hero
    macd1MIN = modules.MACD.apply_default(modules.heikin_ashi.heikin_ashi(default))
AttributeError: module 'modules.MACD' has no attribute 'apply_default'`

Regards,
Jose.

**Comment by digitalftl** [comment]
Hi, have you solved this problem?

**Comment by zyairelai** [comment]
Hi Jose,

Simply remove the `strategies.seven` will do.
I had push the fixed version and it is up now!

Besides, the `strategies.seven` is now moved to another trading bot, which is at:
https://github.com/zyairelai/long-term-low-leverage

The reason is that `futures-hero` is focus on scalping strategies, while the swing strategy will move to `long-term-low-leverage`

**Comment by digitalftl** [comment]
Backtest works fine, but I'm getting this error when I run.py. 

```
BTCUSDT
Traceback (most recent call last):
  File "D:\futures-hero\run.py", line 63, in <module>
    lets_make_some_money(pair, leverage, quantity)
  File "D:\futures-hero\run.py", line 23, in lets_make_some_money
    hero = choose_your_fighter.futures_hero(pair)
  File "D:\futures-hero\strategies\combined.py", line 26, in futures_hero
    macd1MIN = modules.MACD.apply_default(modules.heikin_ashi.heikin_ashi(default))
AttributeError: module 'modules.MACD' has no attribute 'apply_default'
```

**Comment by zyairelai** [comment]
Hi digitalftl,

This is because I had change the `MACD.apply_default()` function to `MACD.apply_MACD`
Due to refractor I was missing out this issue.

The newest version had solved this issue. 
Or if you are confortable with refracting the function name by yourself, you can simply chage `apply_deafult` to `apply_MACD`

**Comment by digitalftl** [comment]
I could say you're a _futures_-**hero**
Thank you, problem solved.

**Comment by josemhb** [comment]
Hi zyairelai,

All working now.

Thank you!
